name: "Build and Publish Release"
on:
  push:
    tags:
      - "*"
    branch:
      - feature/*
jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare go environment
        uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'
          cache: true
      - name: Build
        run: |
          go mod download 
          make
      - name: Package for Debian amd64
        id: pack-deb-amd64
        uses: jiro4989/build-deb-action@v2
        with: 
          package: ssh-iam-sync
          package_root: build/ssh-iam-sync-${{ github.ref_name }}-amd64
          maintainer: Dhruman Bhadeshiya
          version: ${{ github.ref_name }}
          arch: 'amd64'
          desc: 'Sync IAM users to SSH authorized_keys'
      - name: Package for Debian arm64
        id: pack-deb-arm64
        uses: jiro4989/build-deb-action@v2
        with: 
          package: ssh-iam-sync
          package_root: build/ssh-iam-sync-${{ github.ref_name }}-arm64
          maintainer: Dhruman Bhadeshiya
          version: ${{ github.ref_name }}
          arch: 'arm64'
          desc: 'Sync IAM users to SSH authorized_keys'
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with: 
          artifacts: "bin/*, ./*.deb"
